/*
 * User_cfg.h
 *
 *  Created on: Aug 6, 2021
 *      Author: Admin
 */

#ifndef TUEDRIVER_DEVICE_USERUART_CFG_USER_CFG_H_
#define TUEDRIVER_DEVICE_USERUART_CFG_USER_CFG_H_






#include "User_Uart_Types.h"
#include "stm32f1xx_hal.h"
#include "Std_Types.h"

#define USER_UART_CHANNEL_LPUART0	0U
#define USER_UART_CHANNEL_LPUART1	1U
#define USER_UART_CHANNEL_LPUART2	2U

#define USER_UART_CHANNEL_USART1	3U
#define USER_UART_CHANNEL_USART2	4U
#define USER_UART_CHANNEL_USART3	5U
#define USER_UART_CHANNEL_USART4	6U
#define USER_UART_CHANNEL_USART5	7U
#define USER_UART_CHANNEL_USART6	8U
//#define USER_UART_CHANNEL_USART6	9U
/*
#define USER_UART_CHANNEL_UART0		0U
#define USER_UART_CHANNEL_UART1		1U
#define USER_UART_CHANNEL_UART2		2U
#define USER_UART_CHANNEL_UART3		3U
#define USER_UART_CHANNEL_UART4		4U
#define USER_UART_CHANNEL_UART5		5U
#define USER_UART_CHANNEL_UART6		6U
#define USER_UART_CHANNEL_UART7		7U
#define USER_UART_CHANNEL_UART8		8U
#endif*/






#define		USER_UART_SOURCECLOCK_CHANNEL_USART1	72000000
#define 	USER_UART_BAUDRATE_CHANNEL_USART1		115200


#define		USER_UART_SOURCECLOCK_CHANNEL_USART2	36000000
#define 	USER_UART_BAUDRATE_CHANNEL_USART2		115200



#define USER_UART_NUMBEROFCHANNEL_USED 2U
#define USER_UART_NUMBEROFHARDWARE_USED 2u

extern const User_Uart_ConfigType  User_Uart_ConfigPtr;

#endif /* TUEDRIVER_DEVICE_USERUART_CFG_USER_CFG_H_ */
