/*
 * User_cfg.c
 *
 *  Created on: Aug 6, 2021
 *      Author: Admin
 */

#include "User_cfg.h"
static const User_Uart_HwConfigType  User_Uart_HwConfig[USER_UART_NUMBEROFCHANNEL_USED] =
{
	{
		USER_UART_CHANNEL_USART1,
		USER_UART_SOURCECLOCK_CHANNEL_USART1,
		USER_UART_BAUDRATE_CHANNEL_USART1,
		USER_UART_PARITYMODE_NONE,
		USER_UART_STOPBITCOUNT_1,
		USER_UART_SLIPSTATUS_DISABLE
	},
	{
		USER_UART_CHANNEL_USART2,
		USER_UART_SOURCECLOCK_CHANNEL_USART2,
		USER_UART_BAUDRATE_CHANNEL_USART2,
		USER_UART_PARITYMODE_NONE,
		USER_UART_STOPBITCOUNT_1,
		USER_UART_SLIPSTATUS_DISABLE
	}
};

const User_Uart_ConfigType  User_Uart_ConfigPtr =
{
	USER_UART_NUMBEROFCHANNEL_USED,
	USER_UART_NUMBEROFHARDWARE_USED,
	(User_Uart_HwConfigType *)User_Uart_HwConfig
};
